cache:
  directories:
    - test/elm-stuff/build-artifacts

language: node_js

node_js:
  - "8.11.2"

install:
  - npm install -g elm@0.19 elm-test@0.19.0-beta9

script:
  - elm-test tests/Tests/Main.elm
